# Generated by Django 6.0.6 on 2026-06-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('exterior', 'Building Exterior Restoration'), ('concrete', 'Outdoor Concrete Restoration & Resurfacing'), ('floor', 'Floor Care & Interior Walls Restoration'), ('roof', 'Tiled Roof Cleaning & Maintenance'), ('waterproofing', 'Waterproofing & Protective Coating'), ('other', 'Other / Not Sure Yet')], default='other', max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (admin only)')),
            ],
            options={
                'verbose_name': 'Client Inquiry',
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
